import * as React from "react"
import { Link } from "gatsby"
import { StaticImage } from "gatsby-plugin-image"

import Layout from "../../../components/layout"
import Seo from "../../../components/seo"

const SecondPage = () => (
  <Layout
    siteTitle="Calling Tools"
    image="map.jpg"
    language="en"
  >
    <Seo
      title="Volunteer!"
      defaultTitle="Calling Tools"
      lang="en"
    />
<StaticImage
  src="../../../images/map.jpg"
/>

<div class="languages"></div>

    <div class="content">
<div><ul><li><Link to="/en/">What Is Calling?</Link></li><li><Link to="/en/personal_well_being">Step 1: Take Care Of Yourself</Link></li><li><Link to="/en/who_am_i/">Step 2: Know Who You Are</Link></li><li><Link to="/en/personal_agency/">Step 3: Take Charge</Link></li><li><Link to="/en/references">References</Link></li></ul></div>

<h1 style={{fontWeight: 'bold', fontSize: "3rem",textAlign: "center",borderBottom: "2px solid black"}}>Volunteer!</h1>

<h1>Volunteer in an organization that is in line with your interests. You're more likely to identify your next steps or "calling" sooner by doing something (even when not getting paid) rather than sitting at home doing nothing.</h1>
<div className="image" style={{width: "50%",float: "right"}}>
<StaticImage
  src="../../../images/volunteer.jpg"
/>
</div>
<ul>
<li><h2>Gives you an opportunity to learn more about your field of interest, build practical skills and cultivate opportunities.</h2></li>
<li><h2>Helps you gain more work experience.</h2></li>
<li><h2>Broadens your network of connections.</h2></li>
<li><h2>The supervisor or other colleagues can provide you with a job reference.</h2></li>
</ul>
<p style={{textAlign: "center"}}><span style={{fontWeight: 400}}>*************************************</span></p>
<div className="quote">
<h3><i>&ldquo;Everybody can be great...because anybody can serve. You don't have to have a college degree to serve. You don't have to make your subject and verb&nbsp;agree to serve. You only need a heart full of grace. A soul&nbsp;generated by love.&rdquo;&nbsp;&nbsp;</i></h3>
<h3><i>--Martin Luther King, Jr.</i></h3>
</div>
<p></p>

    </div>

  </Layout>
)

export default SecondPage
